style:
  ForbiddenImport:
    active: true
    imports: [ 'android.util.Log' ]
    excludes: [ '**/LoggerAndroid.kt' ]
  UseDataClass:
    active: true
    excludes: [ '**/*Copyable.kt' ]
    ignoreAnnotated: [ com.nice.cxonechat.Public ]

exceptions:
  TooGenericExceptionCaught:
    allowedExceptionNameRegex: '_|(ignore|expected|logged).*'

cxone-rules:
  active: true
  ProhibitedCall:
    active: true

libraries:
  ForbiddenPublicDataClass:
    active: true
  LibraryCodeMustSpecifyReturnType:
    active: true
    excludes: [ '**/test/**', '**/**Test**.kt', '**/androidTest/**', '**/*.Spec.kt' ]
    ignoreAnnotated:
      - "org.junit.Test"
  LibraryEntitiesShouldNotBePublic:
    active: false   # We are using minification to prevent usage from applications.
